package es.csic.iiia.nsm.visualization.cbr;

import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author javi
 */
public class CBRPanel extends JPanel implements TreeSelectionListener
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3831394315649334241L;
	
	private JComboBox boxScores;
	private JLabel lblCaseDescription;
	private JLabel lblEffectiveness;
	private JLabel lblNecessity;
	private JLabel lblNorms;
	private JLabel lblSolution;
	private JLabel lblTitle;
	private JLabel lblTreeCases;
	private JProgressBar pbEffectiveness;
	private JProgressBar pbNecessity;
	private JScrollPane scPanelTreeCases;
	private JTree treeCases;
	private JTextField txtCaseDescription;
	private JTextField txtNorms;
	private JTextField txtSolution;

	/**
	 * Creates new form CBRPanel
	 */
	public CBRPanel() {
		this.initComponents();
		this.clear();
	}

	/**
	 * 
	 */
	@Override
	public void valueChanged(TreeSelectionEvent e) {
		DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeCases.getLastSelectedPathComponent();

		// Nothing is selected
		if (node == null)
		{
			
		}
	}

	/**
	 * 
	 */
	private void clear() {
		txtCaseDescription.setText("Case description");
		txtSolution.setText("Case solution");
		txtNorms.setText("Case solution norms");
		pbEffectiveness.setValue(0);
		pbNecessity.setValue(0);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		txtCaseDescription = new JTextField();
		scPanelTreeCases = new JScrollPane();
		treeCases = new JTree();
		txtSolution = new JTextField();
		txtNorms = new JTextField();
		pbEffectiveness = new JProgressBar();
		lblTitle = new JLabel();
		lblEffectiveness = new JLabel();
		lblCaseDescription = new JLabel();
		lblTreeCases = new JLabel();
		lblSolution = new JLabel();
		boxScores = new JComboBox();
		lblNecessity = new JLabel();
		pbNecessity = new JProgressBar();
		lblNorms = new JLabel();

		setBackground(UIManager.getDefaults().getColor("control"));

		scPanelTreeCases.setViewportView(treeCases);

		lblEffectiveness.setText("Effectiveness");
		lblCaseDescription.setText("Description");
		lblTreeCases.setText("Cases");
		lblSolution.setText("Solution");
		lblNecessity.setText("Necessity");
		lblNorms.setText("Norms");
		
		lblTitle.setText("IRON CBR Tracer");
		lblTitle.setBackground(new java.awt.Color(254, 254, 254));
		lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); 
		lblTitle.setForeground(java.awt.Color.darkGray);
		lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
		lblTitle.setBorder(BorderFactory.createLineBorder(java.awt.Color.darkGray));
		
//		boxScores.setModel(new DefaultComboBoxModel(goals));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scPanelTreeCases, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTreeCases))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCaseDescription)
                        .addComponent(txtSolution)
                        .addComponent(txtNorms, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boxScores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNorms))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblEffectiveness)
                                        .addComponent(lblNecessity)))
                                .addComponent(lblCaseDescription)
                                .addComponent(lblSolution))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pbEffectiveness, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(pbNecessity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTreeCases)
                .addComponent(lblCaseDescription))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(txtCaseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblSolution)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pbEffectiveness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pbNecessity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEffectiveness)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblNecessity))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(boxScores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblNorms)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtNorms, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addComponent(scPanelTreeCases))
            .addContainerGap())
    );
	}	
}
